//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationCliente.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>192.168.1.38</string>\r\n  <string>192.168.1.38</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection monday {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["monday"]));
            }
            set {
                this["monday"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>192.168.1.38</string>\r\n  <string>192.168.1.38</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection tuesday {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["tuesday"]));
            }
            set {
                this["tuesday"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>192.168.1.38</string>\r\n  <string>192.168.1.38</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection wednesday {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["wednesday"]));
            }
            set {
                this["wednesday"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>192.168.1.38</string>\r\n  <string>192.168.1.38</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection thursday {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["thursday"]));
            }
            set {
                this["thursday"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>192.168.1.38</string>\r\n  <string>192.168.1.38</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection friday {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["friday"]));
            }
            set {
                this["friday"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>192.168.1.38</string>\r\n  <string>192.168.1.38</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection saturday {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["saturday"]));
            }
            set {
                this["saturday"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsd=\"http://www.w3." +
            "org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n  <s" +
            "tring>192.168.1.38</string>\r\n  <string>192.168.1.38</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection sunday {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["sunday"]));
            }
            set {
                this["sunday"] = value;
            }
        }
    }
}
