//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationTeacher.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int TimeBetweenDemand {
            get {
                return ((int)(this["TimeBetweenDemand"]));
            }
            set {
                this["TimeBetweenDemand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ScreenToShareId {
            get {
                return ((int)(this["ScreenToShareId"]));
            }
            set {
                this["ScreenToShareId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathToSaveFolder {
            get {
                return ((string)(this["PathToSaveFolder"]));
            }
            set {
                this["PathToSaveFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> IgnoredProcesses {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["IgnoredProcesses"]));
            }
            set {
                this["IgnoredProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> AlertedProcesses {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["AlertedProcesses"]));
            }
            set {
                this["AlertedProcesses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> AlertedUrls {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["AlertedUrls"]));
            }
            set {
                this["AlertedUrls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.String> AutorisedWebsite {
            get {
                return ((global::System.Collections.Generic.List<System.String>)(this["AutorisedWebsite"]));
            }
            set {
                this["AutorisedWebsite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.Dictionary<System.String,System.Collections.Generic.List<System.String>> AllFocus {
            get {
                return ((global::System.Collections.Generic.Dictionary<System.String,System.Collections.Generic.List<System.String>>)(this["AllFocus"]));
            }
            set {
                this["AllFocus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int DefaultTimeout {
            get {
                return ((int)(this["DefaultTimeout"]));
            }
            set {
                this["DefaultTimeout"] = value;
            }
        }
    }
}
